# Evaluating Projections/Planning Scenarios


## Definition of a projection

A projection is a statment of the probability of each event within some set or range of events (e.g., number of hospitalizatoins due to some cause, the value of a stock) over
some set of future times, under some set of assumptions or conditions. That is a projections states:

$$
\forall y\in \mathbf{Y} \Pr(y|\mathbf{X})
$$

where $\mathbf{Y}$ is the set of events over which we have projections and $\mathbf{X}$ is the set of assumptions/covariate values under which those projections are meant to apply.

Note that a single value projection in merely a special case where for some value, $y_i$, $\Pr(y_i|\mathbf{X}) = 1$ and
$\forall y_j \text{ where } y_j \neq y_i, \Pr(y_j|\mathbf{X}) = 0$.


## Definition of a forecast

A forecast is a projection where the set of conditional values $\mathbf{X}$ includes all possible states of the universe, $\mathbf{\mathcal{X}}$ given the current state of the universe. So that is, a forecast givens us:

$$\Pr(y|\mathbf{\mathcal{X}})$$

## Definition of a scenario projection

A scenario projection is a projection that is contingent on some set of current or future conditions that are unknown at the time at which the projections is made. That is 

### Assumption: A projection or models performance or utility is only relevant in its ability to inform consequential decisions



### Assumption: A decision is only consequential if it impacts future utility

### Conjecture: The ideal evalution of a projection should contrast the implied utility under that projection versus the real utility

#### Try/Thoughts

Consider a situation where we are unable to modify the probability of the outcomes, and our ability to optimize utility is
completely based on the results of designing around some future value $y$. The realized utility of designing around a 
value $y_d$ is captured by some function $U(y_d, y_a)$ where $y_a$ is the actual value. 

For example, $y$ might be the expected number of people presenting for hospitalization. There is some cost of maintaining an 
extra hospital bed, say 5,000, and an expected cost of someone presenting for hospitalization if we do not have a bed available
reflecting emergency allocation of resources and the increased liklihood of server oucomes, say 25,000 per excess case. Hence $U(y_d, y_a)$
would be:
$$ 
U(y_d, y_a) = 
\begin{cases}
    (-5000)(y_d-y_a) &\text{if } y_d \geq y_a\\
    (-25000)(y_a-y_d) &\text{if } y_a > y_d
\end{cases}
$$

Based on this utility function, the expected utility of some decision given a probabilistic prediction $\mathbfcal{P}$ is:

$$
E(U(y_d)) = \sum_{y \in Y} \Pr(y|\mathbfcal{P})U(y_d,y)
$$

Where $Y$ is the set of all possible outcomes and $\Pr(y|\mathbfcal{P})$
is the probability of $y$ if the prediction $\mathbfcal{P}$ is correct.

Note that this implies an optimal value to design around, $y^*_d$:
$$
\DeclareMathOperator*{\argmax}{argmax}
y^*_d|\mathbfcal{P} = \argmax_{y_d}  \sum_{y \in Y} \Pr(y|\mathbfcal{P})U(y_d,y)
$$

Given this, the error in predicted utility of any probabilistic
prediction can be considered to be:

$$
\left| U(y^*_d|\mathbfcal{P}, y_a) -  \sum_{y \in Y} \Pr(y|\mathbfcal{P})U(y^*_d|\mathbfcal{P},y) \right|
$$


Some properties of this approach:

- The projection implied optimal value to base decisions on is the weighted mean, which in the case of a simple linear error function should be the mean forecast (not the median).

- The error function will penalize under certainty when 
the forecast is correct.




# How should Scenarios be Fit


